kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello-k8s-demo
  type: NodePort
  ports:
  - protocol: TCP
    port:  80
    targetPort:  8080
    nodePort: 30008